name: glp_runtime
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
