name: grassroots_ble
description: Resilient decentralized communication for Grassroots Social Networks using BLE
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Cryptography
  cryptography: ^2.7.0

  # Utilities
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
